In [3]:
import numpy as np
import pandas as pd
import math as mt

In [4]:
#Abbiamo una lista di liste:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [5]:
mat_array = np.array(mat)

In [6]:
mat_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
mat_array.shape

(3, 5)

In [8]:
mat_array[0,:]

array([0, 1, 2, 3, 4])

In [9]:
mat_array[-2,:]

array([5, 6, 7, 8, 9])

In [11]:
print("SENO di 90: ", mt.sin(mt.pi/2),"\n","COSENO di 90: ", mt.cos(mt.pi/2),"\n","SENO di 180: ",mt.sin(mt.pi),"\n","COSENO di 180: ", mt.cos(mt.pi))

SENO di 90:  1.0 
 COSENO di 90:  6.123233995736766e-17 
 SENO di 180:  1.2246467991473532e-16 
 COSENO di 180:  -1.0


In [12]:
      print("FATTORIALE di 4:", mt.factorial(4))

FATTORIALE di 4: 24


In [13]:
mt.degrees(mt.pi)

180.0

In [51]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst)

#ciclo for in range
#for x in range(100,110):
#    print(x)

#ciclo for in range con lo step di avanzamento che possiamo assegnare
#for x in range(0,100,10):
 #   print(x)

#print("vendite mensili:\n")
#for x in range(0,10,2):
#   print(list(range(x,0,-1)))


vendite mensili:

[]
[2, 1]
[4, 3, 2, 1]
[6, 5, 4, 3, 2, 1]
[8, 7, 6, 5, 4, 3, 2, 1]


In [15]:
lst

array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

In [16]:
print("vendita max mensile: ", lst.max())

vendita max mensile:  8150


In [24]:
filter_5k = lst [lst > 4999]
print("vendite maggiori di 4999: ", filter)
print("quanti sono: ", len(filter_5k))

vendite maggiori di 4999:  [5500 7200 6410 8150 7100 5350]
quanti sono:  6


In [23]:
#quali sono le vendite minori di 3000 oggetti?
filter_3k = lst [lst < 3000]
print("vendite minori di 3000: ", filter_3k)
print("quanti sono: ", len(filter_3k))

vendite minori di 3000:  [2000 1280 1900 2500]
quanti sono:  4


In [28]:
#in media quanti oggetti sono stati venduti al mese?
print("media di oggetti venduti: ",lst.mean())
print("media di oggetti venduti arrotondata a 2 decimali: ",round(lst.mean(),2))

media di oggetti venduti:  4634.166666666667
media di oggetti venduti arrotondata a 2 decimali:  4634.17


In [40]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 
                2000: 23_000, 2001: 25_000, 2002: 17_000, 
                  2003: 14_000, 2004: 21_000} 
#struttura dati base di python, i dati sono memorizzati con una tipologia chiave valore

fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 
                              25_000, 17_000, 14_000, 21_000], 
                             index=range(1997, 2005))
#in questo caso invece Pandas fa una gestione virtualizzata dei dati, li organizza e li 
#mostra in forma tabellare 

print("dati di tipo: ",type(fatturati_dict[1997])) 
print("dati di tipo: ",type(fatturati_series[1997]))
print("massimo della serie: ", fatturati_series.max())
print("valori della serie: ", fatturati_series.values) 
print("valori della serie tra\n", fatturati_series[fatturati_series.between(left=15000, right=20000)]) 

dati di tipo:  <class 'int'>
dati di tipo:  <class 'numpy.int64'>
massimo della serie:  25000
valori della serie:  [12000 15000 20000 23000 25000 17000 14000 21000]
valori della serie tra
 1998    15000
1999    20000
2002    17000
dtype: int64


In [46]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )
print (stipendi)

#liste --> parentesi quadre, 
#tuple --> parentesi tonde
#dizionari o set --> parentesi graffe

lista_stipendi_raddoppiati=[]
lista_stipendi_raddoppiati_com=[]
#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: 
#• con un ciclo for 
for  stipendio in stipendi:
    lista_stipendi_raddoppiati.append(stipendio*2)

#list comprehension quando vai a richiamare una riga di codice per dare delle operazioni
lista_stipendi_raddoppiati_com = [stipendio*2 for stipendio in stipendi] 
print("lista stipendi raddoppiati con for", lista_stipendi_raddoppiati)
print("lista stipendi raddoppiati comprehension", lista_stipendi_raddoppiati_com)

#• con il masking
lista_stipendi_raddoppiati_numpy=[]
lista_stipendi_raddoppiati_numpy = stipendi*2
print("lista stipendi raddoppiati masking", lista_stipendi_raddoppiati_numpy)

[ 100  200  300  400  500  600  700  800  900 1000]
lista stipendi raddoppiati con for [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
lista stipendi raddoppiati comprehension [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
lista stipendi raddoppiati masking [ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [60]:
libri = ["enciclopedia", "atlante", "dizionario"] 
for libro in libri: 
    print(libro) 
    
#alternativa con enumerate
for contatore, libro in enumerate(libri): 
    print(contatore, libro)

alunni = ["Lucio", "Silvio", "Michela","Natalia"]
corsi = ["ingegneria", "medicina", "cinema", "giurisprudenza"]
anni = [19,22,25,21]

for alunno, corso, eta in zip(alunni, corsi, anni):
    print(alunno,"frequenta",corso,"e ha", eta, " anni.\n")

nomi = ['Anna', 'Bruno', 'Carla']
età = [28, 34, 29]
persone = zip(nomi, età) #zip permette di iterare contemporanemamente più liste
# Converti l'iteratore in una lista di tuple
lista_persone = list(persone)
print(lista_persone)
for nome, età in zip(nomi, età):
    print(f"{nome} ha {età} anni.") #la f serve per formattare le stringhe

enciclopedia
atlante
dizionario
0 enciclopedia
1 atlante
2 dizionario
Lucio frequenta ingegneria e ha 19  anni.

Silvio frequenta medicina e ha 22  anni.

Michela frequenta cinema e ha 25  anni.

Natalia frequenta giurisprudenza e ha 21  anni.

[('Anna', 28), ('Bruno', 34), ('Carla', 29)]
Anna ha 28 anni.
Bruno ha 34 anni.
Carla ha 29 anni.
